
const express = require('express');
const app = express();
const bodyParser=require('body-parser');
const mongoose=require('mongoose');

const userRoutes = require('./Routes/user');
const cors=require('cors');
app.use(bodyParser.urlencoded({extended:false}));
app.use(bodyParser.json());

const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');
const options = {

  apis: ['./Routes/user.js'],
  
  
  swaggerDefinition: {
    info: {
    
      description: 'Test API with autogenerated swagger doc',
     
      title: 'Flight Swagger Documentation',

    },
    servers:["http://localhost:4000/"]

  },
};
const specs = swaggerJsdoc(options);


mongoose.connect("mongodb+srv://test:test@cluster0.vphey.mongodb.net/Flight?retryWrites=true&w=majority",()=>
{
  console.log("connected")
});
//mongoose.Promise = global.Promise;

app.use(cors());
app.use('/user', userRoutes);
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(specs));


app.use((req, res, next) => {
    const error = new Error("Not found");
    error.status = 404;
    next(error);
  });

  app.use((error, req, res, next) => {
    res.status(error.status || 500);
    res.json({
      error: {
        message: error.message
      }
    });
  });

  module.exports=app;